export const EVT_GET_BIBLIO_ITEMS_LIST = "GET_BIBLIO_ITEMS_LIST";
export const EVT_GET_BIBLIO_ITEMS_LIST_SUCCESS = "GET_BIBLIO_ITEMS_LIST_SUCCESS";
export const EVT_ADD_BIBLIO_ITEM = "ADD_BIBLIO_ITEM";
export const EVT_UPDATE_BIBLIO_ITEM = "UPDATE_BIBLIO_ITEM";
