export const EVT_GET_BORROWERS_LIST = "GET_BORROWERS_LIST";
export const EVT_GET_BORROWERS_LIST_SUCCESS = "GET_BORROWERS_LIST_SUCCESS";
export const EVT_ADD_BORROWER = "ADD_BORROWER";
export const EVT_UPDATE_BORROWER = "UPDATE_BORROWER";
