export const EVT_GET_ITEM_TYPES_LIST = "GET_ITEM_TYPES_LIST";
export const EVT_GET_ITEM_TYPES_LIST_SUCCESS = "GET_ITEM_TYPES_LIST_SUCCESS";
export const EVT_ADD_ITEM_TYPE = "ADD_ITEM_TYPE";
export const EVT_UPDATE_ITEM_TYPE = "UPDATE_ITEM_TYPE";
