export const EVT_GET_USERS_LIST = "GET_USERS_LIST";
export const EVT_GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const EVT_ADD_USER = "ADD_USER";
export const EVT_UPDATE_USER = "UPDATE_USER";
