import { IFieldConfig } from "../constants/types";

export const itemColumnConfig: IFieldConfig[] = [
  {
    field: "biblioItemId",
    title: "Biblio Item",
    type: "dropdown",
    required: true,
    dataSource: "/BiblioItem",
    valueField: "id",
    displayField: "title",
  },
  {
    field: "barCode",
    title: "Bar Code",
    type: "string",
    required: true,
  },
  {
    field: "price",
    title: "Price",
    type: "number",
    required: true,
  },
  {
    field: "replacementPrice",
    title: "Replacement Price",
    type: "number",
    required: true,
  },
  {
    field: "notForLoan",
    title: "Not For Loan",
    type: "checkbox",
    required: true,
  },
  {
    field: "itemStatusCode",
    title: "Item Status Code",
    type: "dropdown",
    required: true,
    dataSource: "/ItemStatus",
    valueField: "itemStatusCode",
    displayField: "itemStatusCodeName",
  },
  {
    field: "itemStatusReportedDate",
    title: "Item Status Reported Date",
    type: "date",
    required: true,
  },
  {
    field: "itemNotes",
    title: "Item Notes",
    type: "string",
    required: true,
  },
  {
    field: "itemNotesNonpublic",
    title: "Item Notes Nonpublic",
    type: "string",
    required: true,
  },
  {
    field: "homeBranchCode",
    title: "Home Branch Code",
    type: "dropdown",
    required: true,
    dataSource: "/Branch",
    valueField: "branch_code",
    displayField: "branch_name",
  },
  {
    field: "branchCode",
    title: "Branch Code",
    type: "dropdown",
    required: true,
    dataSource: "/Branch",
    valueField: "branch_code",
    displayField: "branch_name",
  },
  {
    field: "imageurl",
    hidden: true,
    defaultValue: "string",
  },

  {
    field: "isactive",
    title: "Active",
    type: "checkbox",
    required: true,
    defaultValue: true,
  },
];
